### ISSUE TITLE
Question: Outdated docker nvidia installation guide?

### ISSUE THREAD

**Issue by mischa-ai** [osrf/icra2023_ros2_gz_tutorial#40]
Hey, I'm not sure if it belongs here, but you are [referencing](https://github.com/osrf/subt/wiki/Docker%20Install#install-nvidia-docker) an outdated nvidia docker installation guide, as [nvidia-docker](https://github.com/NVIDIA/nvidia-docker) has been superseded by the [NVIDIA Container Toolkit](https://github.com/NVIDIA/nvidia-container-toolkit).

Thou the reference is the **osrf/subt** repo... as I said don't know if it belongs here or there?

**Comment by mabelzhang** [comment]
Hi, thanks for taking note of this.

As this repo was meant for a tutorial on a specific date, I don't think we'll test a new way now that the tutorial is over.

We chose to do the nvidia-docker way because it was a solid and tested way that we knew will work for the most people, since teams used it for SubT. Since there was already installation instructions there, we just referred there instead of reinventing the wheel.

Deprecation means it still works for the moment. Given the decrease in activity in this repo, I suspect by the time nvidia-docker completely stops working, this repo would not be used very much either, or people will find other ways to install NVIDIA for Docker. If that is not the case, feel free to comment and reopen the issue in the future.

I will add a note to the README for installation, to mention what you said.
